name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Weekly

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Update dependencies
        run: deno task update

      - name: Create lcov file
        run: deno task cov:gen

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.os }}
          files: cov.lcov

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: update dependencies"
          delete-branch: true

